version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
            - ./conf/docker-php.conf:/etc/apache2/conf-enabled/docker-php.conf
        networks:
            - default

