<?php
include("./topo.phtml");
$acao = $_GET['acao'];
switch ($acao) {
    case "cadastrar":
?>
<!-- INICIO FORM -->
 <div class="slider_area">
        <div class="single_slider slider_bg_1 d-flex align-items-center">
            <div class="container">
                <div class="row">
					<div class="col-lg-8 col-md-15">
						<div class="col-lg-1 col-md-2">
                        <div class="slider_text_form">
                            <h3>Cadastre sua <span>ONG!</span></h3>
                        </div>
                    </div>
							<form action="../controller/ong.php">
								<div class="mt-10">
									<input type='hidden' name='a_id' value='1'>
								</div>
								<div class="mt-10">
									<input type='hidden' name='acao' value='cadastrar'>
								</div>
								<div class="mt-10">
									<input type="text" name="nome_fantasia" placeholder="Nome fantasia"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nome Social'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="nome_social" placeholder="Nome Social"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nome Social'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="registro_cartorio" placeholder="Registro Cartorio"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Registro Cartorio'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="endereco" placeholder="Endereço"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Rua A'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="numero_endereco" placeholder="Número"
										onfocus="this.placeholder = ''" onblur="this.placeholder = '000'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="bairro" placeholder="Bairro"
										onfocus="this.placeholder = ''" onblur="this.placeholder = '000'" required
										class="single-input">
									</div>
								<div class="mt-10">
									<input type="text" name="cep" placeholder="CEP"
										onfocus="this.placeholder = ''" onblur="this.placeholder = '000'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="estado" placeholder="ESTADO"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'RS'" required
										class="single-input">
								</div>							
								<div class="mt-10">
									<input type="email" name="email" placeholder="E-mail"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'seu_email@dominio.com.br'" required
										class="single-input">
								</div>
								<div class="my-1">
        							<div class="col-md-12 text-center">
										<button type="submit" class="boxed-btn4" >Cadastrar!</button>
        							</div>
    							</div>
							</form>
					</div>
				</div>
        
			</div>		
		</div>
           	<div class="dog_thumb_form d-none d-lg-block">
            	<img src="img/banner/dog.png" alt="">
            </div>
</div>
 <!-- FIM FORM -->       
<?php
		break;
 	case "editar":

		include("../model/class.ong.php");
		$ong = new ong(); 
		$ong->setId(1);
		$dados = $ong->busca();
		var_dump($dados);
		foreach ($dados as $dado) {
echo"<div class='slider_area'>
        <div class='single_slider slider_bg_1 d-flex align-items-center'>
            <div class='container'>
                <div class='row'>
                    <div class='col-lg-8 col-md-15'>
                        <div class='col-lg-1 col-md-10'>
                        <div class='slider_text_form'>
                            <h3>Atualize sua <span>ONG!</span></h3>
                        </div>
                    </div>
                            <form action='../controller/ong.php'>
                                <div class='mt-10'>
                                    <input type='hidden' name='a_id' value='1'>
                                </div>
                                <div class='mt-10'>
                                    <input type='hidden' name='acao' value='editar'>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='nome_fantasia' placeholder='Nome fantasia'
                                        class='single-input' required value={$dado['nome_fantasia']} >
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='nome_social' placeholder='Nome Social'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'Nome Social'' 
                                        class='single-input' required value={$dado["nome_social"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='registro_cartorio' placeholder='Registro Cartorio'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'Registro Cartorio'' required
                                        class='single-input' value={$dado["registro_cartorio"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='endereco' placeholder='Endereço'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'Rua A'' required
                                        class='single-input' value={$dado["endereco"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='numero_endereco' placeholder='Número'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = '000'' required
                                        class='single-input' value={$dado["numero_endereco"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='bairro' placeholder='Bairro'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = '000'' required
                                        class='single-input' value={$dado["bairro"]}>
                                    </div>
                                <div class='mt-10'>
                                    <input type='text' name='cep' placeholder='CEP'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = '000'' required
                                        class='single-input' value={$dado["cep"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='estado' placeholder='ESTADO'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'RS'' required
                                        class='single-input' value={$dado["estado"]}>
                                </div>                          
                                <div class='mt-10'>
                                    <input type='email' name='email' placeholder='E-mail'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'seu_email@dominio.com.br'' required
                                        class='single-input' value={$dado["email"]}>
                                </div>
                                <div class='my-1'>
                                    <div class='col-md-12 text-center'>
                                        <button type='submit' class='boxed-btn4' >Salvar!</button>
                                    </div>
                                </div>
                            </form>
					</div>
				</div>
        
			</div>		
		</div>
           	<div class='dog_thumb_form d-none d-lg-block'>
            	<img src='img/banner/dog.png' alt='''>
            </div>
</div>
";
		}
		break;
    case "exibir":
        echo "i equals 2";
        break;
}
 
include("rodape.phtml");
?>


