<?php
include("./topo.phtml");
$acao = $_GET['acao'];
switch ($acao) {
    case "cadastrar":
?>
<!-- INICIO FORM -->
 <div class="slider_area">
        <div class="single_slider slider_bg_1 d-flex align-items-center">
            <div class="container">
                <div class="row">
					<div class="col-lg-8 col-md-15">
						<div class="col-lg-1 col-md-2">
                        <div class="slider_text_form">
                            <h3>Cadastre sua <span>ONG!</span></h3>
                        </div>
                    </div>
							<form action="../controller/ong.php">
								<div class="mt-10">
									<input type='hidden' name='a_id' value='1'>
								</div>
								<div class="mt-10">
									<input type='hidden' name='acao' value='cadastrar'>
								</div>
								<div class="mt-10">
									<input type="text" name="nome_fantasia" placeholder="Nome fantasia"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nome Social'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="nome_social" placeholder="Nome Social"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nome Social'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="registro_cartorio" placeholder="Registro Cartorio"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Registro Cartorio'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="endereco" placeholder="Endereço"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'Rua A'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="numero_endereco" placeholder="Número"
										onfocus="this.placeholder = ''" onblur="this.placeholder = '000'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="bairro" placeholder="Bairro"
										onfocus="this.placeholder = ''" onblur="this.placeholder = '000'" required
										class="single-input">
									</div>
								<div class="mt-10">
									<input type="text" name="cep" placeholder="CEP"
										onfocus="this.placeholder = ''" onblur="this.placeholder = '000'" required
										class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="estado" placeholder="ESTADO"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'RS'" required
										class="single-input">
								</div>							
								<div class="mt-10">
									<input type="email" name="email" placeholder="E-mail"
										onfocus="this.placeholder = ''" onblur="this.placeholder = 'seu_email@dominio.com.br'" required
										class="single-input">
								</div>
								<div class="my-1">
        							<div class="col-md-12 text-center">
										<button type="submit" class="boxed-btn4" >Cadastrar!</button>
        							</div>
    							</div>
							</form>
					</div>
				</div>
        
			</div>		
		</div>
           	<div class="dog_thumb_form d-none d-lg-block">
            	<img src="img/banner/dog.png" alt="">
            </div>
</div>
 <!-- FIM FORM -->       
<?php
		break;
 	case "editar":

		include("../model/class.ong.php");
		$ong = new ong(); 
		$ong->setId(1);
		$dados = $ong->busca();
		foreach ($dados as $dado) {
echo"<div class='slider_area'>
        <div class='single_slider slider_bg_1 d-flex align-items-center'>
            <div class='container'>
                <div class='row'>
                    <div class='col-lg-8 col-md-15'>
                        <div class='col-lg-1 col-md-10'>
                        <div class='slider_text_form'>
                            <h3>Atualize sua <span>ONG!</span></h3>
                        </div>
                    </div>
                            <form action='../controller/ong.php'>
								<div class='mt-10'>
									<input type='hidden' name='id' value={$dado['id']}>
								</div>
                                <div class='mt-10'>
                                    <input type='hidden' name='a_id' value={$dado['a_id']}>
                                </div>
                                <div class='mt-10'>
                                    <input type='hidden' name='acao' value='editar'>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='nome_fantasia' placeholder='Nome fantasia'
                                        class='single-input' required value={$dado['nome_fantasia']} >
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='nome_social' placeholder='Nome Social'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'Nome Social'' 
                                        class='single-input' required value={$dado["nome_social"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='registro_cartorio' placeholder='Registro Cartorio'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'Registro Cartorio'' required
                                        class='single-input' value={$dado["registro_cartorio"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='endereco' placeholder='Endereço'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'Rua A'' required
                                        class='single-input' value={$dado["endereco"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='numero_endereco' placeholder='Número'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = '000'' required
                                        class='single-input' value={$dado["numero_endereco"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='bairro' placeholder='Bairro'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = '000'' required
                                        class='single-input' value={$dado["bairro"]}>
                                    </div>
                                <div class='mt-10'>
                                    <input type='text' name='cep' placeholder='CEP'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = '000'' required
                                        class='single-input' value={$dado["cep"]}>
                                </div>
                                <div class='mt-10'>
                                    <input type='text' name='estado' placeholder='ESTADO'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'RS'' required
                                        class='single-input' value={$dado["estado"]}>
                                </div>                          
                                <div class='mt-10'>
                                    <input type='email' name='email' placeholder='E-mail'
                                        onfocus='this.placeholder = ''' onblur='this.placeholder = 'seu_email@dominio.com.br'' required
                                        class='single-input' value={$dado["email"]}>
                                </div>
                                <div class='my-1'>
                                    <div class='col-md-12 text-center'>
                                        <button type='submit' class='boxed-btn4' >Salvar!</button>
                                    </div>
                                </div>
                            </form>
					</div>
				</div>
        
			</div>		
		</div>
           	<div class='dog_thumb_form d-none d-lg-block'>
            	<img src='img/banner/dog.png' alt='''>
            </div>
</div>
";
		}
		break;
	default:
	include("../model/class.ong.php");
	$ong = new ong(); 
	$ong->setId(1);
	$dados = $ong->busca();
	foreach ($dados as $dado) {

	echo "<div class='slider_area'>
			<div class='single_slider slider_bg_1 d-flex align-items-center'>
				<div class='container'>
			<div class='pet_care_area'>
        	<div class='container'>
            	<div class='row align-items-center'>
                	<div class='col-lg-5 col-md-6'>
                    	<div class='pet_thumb'>
                        	<img src='img/about/pet_care.png' alt=''>
                    </div>
                </div><div class='col-lg-6 offset-lg-1 col-md-6'>
				<div class='pet_info'>
				<div class='teste'>
					<div class='section_title' >
						<h3>
							<span>Dados de sua ONG!</span>
						</h3>
						<br>
							<pp>Nome Fantasia: <b>{$dado["nome_fantasia"]}</pp></b><br></b>
							<pp>Nome Social:<b> {$dado["nome_social"]}</pp><br></b>
							<pp>Registro Cartorio:</b> {$dado["registro_cartorio"]}</pp><br></b>
							<pp>Endereço:<b> {$dado["endereco"]}</b> nº:<b> {$dado["numero_endereco"]}</pp><br></b>
							<pp>Bairro:<b> {$dado["bairro"]}</pp><br></b>
							<pp>CEP:<b> {$dado["cep"]}</pp><br></b>
							<pp>Estado:<b> {$dado["estado"]}</pp><br></b>
							<pp>E-mail: <b> {$dado["email"]}</pp><br></b>
							<div class='my-1'>
							<div class='col-md-12 text-center'><br>
								<a href='./ong.phtml?acao=editar' class='boxed-btn3'>Edita</a>
							</div>
					</div>
				</div>
							</div>	</div>
				
						</div>
						</div>
					</div>
				</div>			
			
		</div>		</div>		
	
	
	</div>
							";
	}
							break;
}
 
include("rodape.phtml");
?>